# Generated by Django 4.1.3 on 2023-08-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0002_vendedor_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='vendedores/'),
        ),
    ]
