# Generated by Django 4.1.3 on 2023-08-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0004_alter_vendedor_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='numero_whatsapp',
            field=models.CharField(default=525578553089, max_length=20),
        ),
    ]
