# Generated by Django 4.1.3 on 2023-08-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0007_vendedor_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='numero_whatsapp',
            field=models.CharField(default=5578553089, max_length=20),
        ),
    ]
