# Generated by Django 4.1.3 on 2023-09-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0012_horariodisponible_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horariodisponible',
            old_name='activo',
            new_name='horario_activo',
        ),
    ]
