# Generated by Django 4.1.3 on 2023-10-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0014_categoria_vendedor_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='categoria',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
